// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package workflow

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyValueDouble struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyValueDouble(buf []byte, offset flatbuffers.UOffsetT) *KeyValueDouble {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyValueDouble{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyValueDoubleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyValueDouble(buf []byte, offset flatbuffers.UOffsetT) *KeyValueDouble {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyValueDouble{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyValueDoubleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyValueDouble) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyValueDouble) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyValueDouble) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyValueDouble) Value() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *KeyValueDouble) MutateValue(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func KeyValueDoubleStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KeyValueDoubleAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func KeyValueDoubleAddValue(builder *flatbuffers.Builder, value float64) {
	builder.PrependFloat64Slot(1, value, 0.0)
}
func KeyValueDoubleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
