// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package workflow

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyValueString struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyValueString(buf []byte, offset flatbuffers.UOffsetT) *KeyValueString {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyValueString{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyValueStringBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyValueString(buf []byte, offset flatbuffers.UOffsetT) *KeyValueString {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyValueString{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyValueStringBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyValueString) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyValueString) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyValueString) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyValueString) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func KeyValueStringStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KeyValueStringAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func KeyValueStringAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func KeyValueStringEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
