// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package workflow

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NodeOutputEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsNodeOutputEntry(buf []byte, offset flatbuffers.UOffsetT) *NodeOutputEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NodeOutputEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishNodeOutputEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNodeOutputEntry(buf []byte, offset flatbuffers.UOffsetT) *NodeOutputEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NodeOutputEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNodeOutputEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NodeOutputEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NodeOutputEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NodeOutputEntry) NodeName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeOutputEntry) Output() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NodeOutputEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NodeOutputEntryAddNodeName(builder *flatbuffers.Builder, nodeName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeName), 0)
}
func NodeOutputEntryAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(output), 0)
}
func NodeOutputEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
