// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package workflow

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimerWaitEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsTimerWaitEntry(buf []byte, offset flatbuffers.UOffsetT) *TimerWaitEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimerWaitEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishTimerWaitEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTimerWaitEntry(buf []byte, offset flatbuffers.UOffsetT) *TimerWaitEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TimerWaitEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTimerWaitEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TimerWaitEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimerWaitEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimerWaitEntry) NodeName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TimerWaitEntry) FireAt() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimerWaitEntry) MutateFireAt(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func TimerWaitEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TimerWaitEntryAddNodeName(builder *flatbuffers.Builder, nodeName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeName), 0)
}
func TimerWaitEntryAddFireAt(builder *flatbuffers.Builder, fireAt int64) {
	builder.PrependInt64Slot(1, fireAt, 0)
}
func TimerWaitEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
