linters:
  enable:
    # Basic linters
    - gofmt
    - goimports
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - bodyclose
    # Security focused linters
    - gosec
    - noctx
    # Style linters
    - revive
    #- gofumpt        # Stricter gofmt
    - gci            # Control Go package import order
    # Performance linters
    - prealloc
    - misspell
    - copyloopvar    # Re-enabled for loop variable checking
    - predeclared    # Find code that shadows predeclared identifiers
    # Advanced linters
    - gocritic
    - nilnil         # Checks that there is no simultaneous return of nil error and invalid value
    - errorlint      # Finds code that will cause problems with the error wrapping scheme
    - thelper        # Detects test helpers without t.Helper()
    - tparallel      # Detects inappropriate usage of t.Parallel()

linters-settings:
  gosec:
    excludes:
      - G204 # Disable subprocess command check only when necessary for Tor integration

  govet:
    # check-shadowing is removed as it's deprecated
    settings:
      printf:
        funcs:
          - Debugf
          - Infof
          - Warnf
          - Errorf
          - Fatalf

  errcheck:
    check-type-assertions: true
    check-blank: true
    # Exclude common functions in tests
    exclude-functions:
      - (*testing.T).Error
      - (*testing.T).Fatal
      - (*testing.T).Fatalf
      - (*testing.T).Errorf

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - checkPrivateReceivers
          - disableStutteringCheck
      - name: unused-parameter
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false

  gofumpt:
    extra-rules: true

  gci:
    sections:
      - standard
      - default
      - prefix(flow-orchestrator)

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude all linters for test files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - unused
        - govet
        - ineffassign
        - revive
        - staticcheck
        - noctx
        - bodyclose
    # Exclude some specific linters for benchmark files
    - path: benchmark
      linters:
        - prealloc
        - errcheck
  
  # Moved from run.skip-dirs
  exclude-dirs:
    - tests/testdata
  
  # Moved from run.skip-files
  exclude-files:
    - ".*_test.go$"
    - "test_.*\\.go$"

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  # Skip-dirs and skip-files are removed as they're deprecated
  go: '1.24'
  modules-download-mode: readonly

# Output configuration
output:
  # Only using the new formats option without the deprecated format option
  formats: 
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true 