// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package workflow

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyValueInt struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyValueInt(buf []byte, offset flatbuffers.UOffsetT) *KeyValueInt {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyValueInt{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyValueIntBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyValueInt(buf []byte, offset flatbuffers.UOffsetT) *KeyValueInt {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyValueInt{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyValueIntBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyValueInt) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyValueInt) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyValueInt) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyValueInt) Value() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KeyValueInt) MutateValue(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func KeyValueIntStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KeyValueIntAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func KeyValueIntAddValue(builder *flatbuffers.Builder, value int32) {
	builder.PrependInt32Slot(1, value, 0)
}
func KeyValueIntEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
