// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package workflow

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyValueBool struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyValueBool(buf []byte, offset flatbuffers.UOffsetT) *KeyValueBool {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyValueBool{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyValueBoolBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyValueBool(buf []byte, offset flatbuffers.UOffsetT) *KeyValueBool {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyValueBool{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyValueBoolBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyValueBool) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyValueBool) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyValueBool) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyValueBool) Value() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *KeyValueBool) MutateValue(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func KeyValueBoolStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KeyValueBoolAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func KeyValueBoolAddValue(builder *flatbuffers.Builder, value bool) {
	builder.PrependBoolSlot(1, value, false)
}
func KeyValueBoolEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
