name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m --issues-exit-code=1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - name: Install FlatBuffers compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y flatbuffers-compiler
      - name: Generate FlatBuffers code
        run: make generate-fb
      - name: Generate coverage report for codecov
        run: make codecov-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          fail_ci_if_error: false

  coverage:
    name: Coverage Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - name: Install FlatBuffers compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y flatbuffers-compiler
      - name: Generate FlatBuffers code
        run: make generate-fb
      - name: Install bc
        run: sudo apt-get install -y bc
      - name: Generate focused coverage report
        run: make test-coverage-focused
      - name: Generate coverage report
        run: make coverage-report
      - name: Check coverage thresholds
        run: ./scripts/testing/check_coverage.sh
      - name: Archive coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage-focused.txt
            coverage-focused.html

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - name: Install FlatBuffers compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y flatbuffers-compiler
      - name: Generate FlatBuffers code
        run: make generate-fb
      - name: Build
        run: go build -v ./...
      - name: Run examples
        run: |
          for example in $(find examples -name "main.go" -not -path "*/\.*" | sort); do
            dir=$(dirname $example)
            echo "Running example: $dir"
            cd $dir && go build -v && cd -
          done 