name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write  # Needed for SLSA provenance

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      
      - name: Install FlatBuffers compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y flatbuffers-compiler
      
      - name: Generate FlatBuffers code
        run: make generate-fb
      
      - name: Run Tests
        run: go test -v ./...
      
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: flow-orchestrator.spdx.json
      
      # Extract version from tag
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: true  # Set to true for alpha/beta releases
          files: flow-orchestrator.spdx.json
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true

  # Add SLSA provenance generation
  provenance:
    needs: [release]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_go_slsa3.yml@v2.1.0
    with:
      go-version: '1.24'
      evaluated-envs: "GOFLAGS=-trimpath" 